config/routes.rb
Rails.application.routes.draw do
  resources :support_sessions, only: [:show, :create] do
    member do
      post :take_step
      post :write
      post :wait
      post :attach
      post :finish
    end
  end

  namespace :chatra do
    post :take_step
  end

  resources :steps
  resources :support_session_steps

  root "demo#welcome"
end

app/models/step.rb
class Step < ApplicationRecord
  include AttachedToDataset
  
  validates :type, presence: true

  def evaluate support_session, params
  end

  def step support_session
    SupportSessionStep.where(step: self, support_session: support_session).last
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:edit, :update, :destroy]
  def index
    @steps = Step.all
  end

  def new
    @step = Step.new
  end

  def create
    @step = Step.new(step_params)
    if @step.save
      flash[:notice] = I18n.t('flash.steps.create.notice')
      redirect_to steps_url
    else
      flash[:alert] = I18n.t('flash.steps.create.alert')
      render :new
    end
  end

  def edit
  end

  def update
    if @step.update(step_params)
      flash[:notice] = I18n.t('flash.steps.update.notice')
      redirect_to steps_url
    else
      flash[:alert] = I18n.t('flash.steps.update.alert')
      render :edit
    end
  end

  def destroy
    @step.destroy
    flash[:notice] = I18n.t('flash.steps.destroy.notice')
    redirect_to steps_url
  end

  private
    def step_params
      params.require(:step).permit(
        :type, 
        :text, 
        :value_type, 
        :value_name,
        :action_name,
        :description
      )
    end

    def set_step
      @step = Step.find(params[:id])
    end
end

app/helpers/steps_helper.rb
module StepsHelper
  def step_types 
    {}.tap do |hash|
      [AlertStep, PromptStep, ServerStep].each do |step|
        hash[step.model_name.human] = step.name
      end
    end
  end
end

app/views/steps/_form.html.erb
<%= simple_form_for @step.becomes(Step) do |f| %>
  <%= f.input :type, collection: step_types %>
  <div class="step AlertStep">
    <%= f.input :text %>
  </div>
  <div class="step PromptStep">
    <%= f.input :value_name %>
    <%= f.input :value_type %>
  </div>
  <div class="step ServerStep">
    <%= f.input :action_name %>
    <%= f.input :description %>
  </div>
  <%= f.submit "Save" %>
<% end %>

app/views/steps/edit.html.erb
<%= render "form" %>

app/views/steps/index.html.erb
<% @steps.each do |step| %>
  <div class="step <%= step_type(step) %>">
    <%= render "steps/index/#{step_type(step)}", step: step %>
    <% if step_type(step) != "finish" %>
      <%= link_to t("scope.steps.edit"), edit_step_url(step) %>
      <%= link_to t("scope.steps.destroy"), step_url(step), method: :delete, data: {confirm: I18n.t('scope.steps.confirm_destroy')} %>
    <% end %>
  </div>
<% end %>
<%= link_to t("scope.steps.new"), new_step_url %>

app/views/steps/new.html.erb
<%= render "form" %>